# Generated by Django 4.1.2 on 2022-10-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_ad_rubric_squashed_0004_spare_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
    ]
